releaseName: harbor
parameters:
  AdminPassword:
    NoEcho: true
    Type: String
    Label:
      en: Admin Password
      zh-cn: 管理员密码
    AssociationProperty: ALIYUN::ECS::Instance::Password
values:
  service:
    type: LoadBalancer
  postgresql:
    enabled: true
    adminPassword:
      Ref: AdminPassword
    primary:
      persistence:
        enabled: true
        storageClass: alicloud-disk-essd
        size: 40Gi
waitUntils:
  - Kind: Service
    Name: harbor-server
    JsonPath: $.status.loadBalancer.ingress[0].ip
    Operator: NotEmpty
    FirstMatch: true
    Timeout: 300
outputs:
  Kind: Service
  Name: harbor-server
  JsonPath: $.status.loadBalancer.ingress[0].ip
protocol: https
